# Specifies the active locale_XX.yml file, stored in plugins/LaunchMe/locale.
locale: "EN"
# How far below the cannon block should the sign be?
depth: 1
transports:
    cannon:
        # Block that will deactivate a cannon.
        deactivate: 42
        # Is transport enabled?
        enabled: true
        # Height the cannons deposit you at to fall from.
        height: 600
    teleporter:
        # Block that will deactivate a teleporter.
        deactivate: 42
        # Is transport enabled?
        enabled: true
    land:
        # Is transport enabled?
        enabled: true
    target:
        # Is transport enabled?
        enabled: true
#Set to false to not show the plugin name on teleport.
name: true