name: LaunchMe
main: net.bitjump.launchme.LaunchMe
version: 2.2.1
softdepend: [Vault]
author: Spudstabber
permissions:
    launchme.*:
        description: Gives access to all launchme areas.
        children:
            launchme.cannon.create: true
            launchme.cannon.use: true
            launchme.teleporter.create: true
            launchme.teleporter.use: true
            launchme.land.create: true
            launchme.land.use: true
            launchme.target.create: true
            launchme.tcannon.create: true
            launchme.tcannon.use: true
        default: op
    launchme.cannon.create:
        description: Allows you to create [cannon] signs.
        default: false
    launchme.cannon.use:
        description: Fires you from a cannon!
        default: true
    launchme.teleporter.create:
        description: Allows you to create [teleporter] signs.
        default: false
    launchme.teleporter.use:
        description: Teleports you!
        default: true
    launchme.land.create:
        description: Allows you to create [land] signs.
        default: false
    launchme.land.use:
        description: Allows you to use landing pads.
        default: true
    launchme.target.create:
        description: Allows you to create [target] signs.
        default: false
    launchme.tcannon.create:
        description: Allows you to create [tcannon] signs.
        default: false
    launchme.tcannon.use:
        description: Allows you to use targeted cannons.
        default: true
