name: LaunchMe
main: net.bitjump.launchme.LaunchMe
version: 2.4.1
softdepend: [Vault]
author: Spudstabber
commands:
    launchme:
        description: The LaunchMe master command.
        usage: /<command> [subcommand]
        aliases: [lm]
permissions:
    launchme.*:
        description: Gives access to all launchme areas.
        children:
            launchme.cannon.create: true
            launchme.cannon.use: true
            launchme.teleporter.create: true
            launchme.teleporter.use: true
            launchme.land.create: true
            launchme.land.use: true
            launchme.target.create: true
            launchme.tcannon.create: true
            launchme.tcannon.use: true
            launchme.tteleporter.create: true
            launchme.tteleporter.use: true
            launchme.info: true
            launchme.help: true
            launchme.warp: true
            launchme.warps: true
        default: op
    launchme.cannon.create:
        description: Allows you to create [cannon] signs.
        default: false
    launchme.cannon.use:
        description: Fires you from a cannon!
        default: true
    launchme.teleporter.create:
        description: Allows you to create [teleporter] signs.
        default: false
    launchme.teleporter.use:
        description: Teleports you!
        default: true
    launchme.land.create:
        description: Allows you to create [land] signs.
        default: false
    launchme.land.use:
        description: Allows you to use landing pads.
        default: true
    launchme.target.create:
        description: Allows you to create [target] signs.
        default: false
    launchme.tcannon.create:
        description: Allows you to create [tcannon] signs.
        default: false
    launchme.tcannon.use:
        description: Allows you to use targeted cannons.
        default: true
    launchme.tteleporter.create:
        description: Allows you to create [tteleporter] signs.
        default: false
    launchme.tteleporter.use:
        description: Allows you to use targeted teleporters.
        default: true
    launchme.info:
        description: Allows you to check LaunchMe information.
        default: true
    launchme.help:
        description: Allows you to check LaunchMe command help.
        default: true
    launchme.warp:
        description: Allows you to warp to LaunchMe targets.
        default: false
    launchme.warps:
        description: Allows you to list LaunchMe targets.
        default: false